config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "folders#index"
  resources :users, only: [:edit, :update]
  resources :folders do
    resources :notes
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :folder_users
  has_many :users, through: :folder_users
  has_many :notes
  
  validates :name, presence: true
end

app/models/folder_user.rb
class FolderUser < ApplicationRecord
  belongs_to :folder
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :folder
  belongs_to :user  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :folder_users
  has_many :folders, through: :folder_users
  has_many :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
   
  def index
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(folder_params)
    if @folder.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def folder_params
    params.require(:folder).permit(:name, user_ids: [])
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @folder = Folder.find(params[:folder_id])
    @notes = @folder.notes.includes(:user)
  end

  def new
    @note = Note.new
    @folder = Folder.find(params[:folder_id])
    @notes = @folder.notes.includes(:user)
  end

  def create
    @folder = Folder.find(params[:folder_id])
    @note = @folder.notes.new(note_params)
    if @note.save
      redirect_to folder_notes_path(@folder)
    else
      @notes = @folder.notes.includes(:user)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @note = Note.find(params[:id])
    @folder = Folder.find(params[:folder_id])
    @notes = @folder.notes.includes(:user)
  end

  def update
    @note = Note.find(params[:id])
    @folder = Folder.find(params[:folder_id])
    if @note.update(note_params)
      redirect_to edit_folder_note_path(@folder, @note)
    else
      @notes = @folder.notes.includes(:user)
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def note_params
    params.require(:note).permit(:content, :title).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/folders/index.html.erb
<%= render "shared/header" %>
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "notes/side_bar" %>
  </div>

</div>

app/views/folders/new.html.erb
<div class='chat-room-form'>
  <h1>新規フォルダ作成</h1>
  <%=form_with model: @folder, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :フォルダ名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'フォルダ名を入力して下さい'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>閲覧・編集可能メンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <label>権限を付与するユーザーを選択してください</label><br>
        <% User.where.not(id: current_user.id).each do |user| %>
          <div>
            <%= check_box_tag "folder[user_ids][]", user.id %>
            <%= user.name %>
          </div>
        <% end %>
        <%= hidden_field_tag "folder[user_ids][]", current_user.id %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_edit_note.html.erb
<div class="edit-note">
  <%= form_with model: [@folder, @note], class: 'form', local: true do |f| %>
    <div class="form-input">
        <%= f.text_field :title, class: 'form-title', placeholder: 'タイトルを入力' %>
        <%= f.text_area :content, class: 'form-message', placeholder: '本文を入力' %>
    </div>
    <%= f.submit '保存', class: 'form-submit' %>
  <% end %>
</div>

app/views/notes/_main_note.html.erb
<div class="main-note">
  <div class="note-header">
    <div class="folder-title">
      <%= @folder.name %>
    </div>
    <div class="note-header">
        <div class="create-note">
          <%= link_to "➕新規ノートを作成", new_folder_note_path %>
        </div>
    </div>
  </div>
  <% @folder.notes.each do |note| %>
    <div class="note">
      <div class="note-title">
        <%= link_to note.title, edit_folder_note_path(@folder, note) %>
      </div>
      <div class="note-content">
        <%= link_to note.content, edit_folder_note_path(@folder, note) %>
      </div>
      <div class="note-user">
        <%= note.user.name %>
      </div>
      <div class="note-date">
        <%= l note.created_at %>
      </div>
    </div>
   <% end %>
</div>

app/views/notes/_side_bar.html.erb
<div class="create-folder">
    <%= link_to "➕新規フォルダを作成", new_folder_path %>
</div>

<div class="side-contents">
  <% current_user.folders.each do |folder| %>
    <div class="folder">
      <div class="folder-name">
        <%= link_to folder.name, folder_notes_path(folder) %></a>
      </div>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<%= render "shared/header" %>
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="main-note">
    <%= render "main_note" %>
  </div>
  <div class="edit-note">
    <%= render "edit_note" %>
  </div>
</div>

app/views/notes/index.html.erb
<%= render "shared/header" %>
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="main-note">
    <%= render "main_note" %>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="header">
  <div class="logo">
    <%= link_to "Note App", root_path %>
  </div>
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
</header>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>